import { jsPDF } from 'jspdf';
import 'jspdf-autotable';

interface MatchReportData {
    homeTeam: string;
    awayTeam: string;
    homeScore: number;
    awayScore: number;
    date: string;
    venue: string;
    competition: string;
    events: Array<{ minute: string; type: string; player: string; team: string }>;
    refereeName: string;
    refereeSignature?: string; // base64
    homeCoachSignature?: string; // base64
    awayCoachSignature?: string; // base64
}

export const generateMatchReport = (data: MatchReportData) => {
    const doc = new jsPDF();
    const brandObsidian = '#000000';
    const brandOrange = '#FF4D00';
    const grayLight = '#F8FAFC';

    // 1. Header (Kinetic Order Style)
    doc.setFillColor(brandObsidian);
    doc.rect(0, 0, 210, 45, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(28);
    doc.setFont('helvetica', 'bold');
    doc.text('OFFICIAL MATCH PROTOCOL', 105, 22, { align: 'center' });
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(data.competition.toUpperCase() + ' — SEASON 2026', 105, 32, { align: 'center' });

    // 2. Scoreboard Banner
    doc.setFillColor(grayLight);
    doc.rect(20, 60, 170, 30, 'F');
    
    doc.setTextColor(brandObsidian);
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text(data.homeTeam.toUpperCase(), 65, 80, { align: 'right' });
    doc.text(data.awayTeam.toUpperCase(), 145, 80, { align: 'left' });
    
    doc.setTextColor(brandOrange);
    doc.setFontSize(36);
    doc.text(`${data.homeScore} - ${data.awayScore}`, 105, 81, { align: 'center' });

    // 3. Match Details
    doc.setTextColor(100, 116, 139);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.text('DATE', 20, 105);
    doc.text('VENUE', 105, 105);
    
    doc.setTextColor(brandObsidian);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.text(data.date, 20, 112);
    doc.text(data.venue.toUpperCase(), 105, 112);

    // 4. Events Table
    if (data.events.length > 0) {
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text('MATCH TIMELINE', 20, 130);
        
        (doc as any).autoTable({
            startY: 135,
            head: [['MIN', 'EVENT', 'PLAYER', 'TEAM']],
            body: data.events.map(e => [e.minute + "'", e.type.replace('_', ' ').toUpperCase(), e.player, e.team]),
            headStyles: { fillColor: [0, 0, 0], textColor: [255, 255, 255], fontStyle: 'bold' },
            styles: { fontSize: 10, cellPadding: 6 },
            margin: { left: 20, right: 20 },
            alternateRowStyles: { fillColor: [249, 250, 251] }
        });
    }

    // 5. Official Verification & Signatures
    const finalY = (doc as any).lastAutoTable?.finalY || 140;
    const sigY = Math.max(finalY + 20, 200);

    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('OFFICIAL VERIFICATION', 20, sigY);
    doc.line(20, sigY + 2, 190, sigY + 2);

    // Signature Slots
    const sigSlotWidth = 50;
    const sigSlotHeight = 25;

    // Referee
    doc.setFontSize(8);
    doc.text('REFEREE SIGNATURE', 20, sigY + 10);
    doc.rect(20, sigY + 12, sigSlotWidth, sigSlotHeight);
    if (data.refereeSignature) {
        doc.addImage(data.refereeSignature, 'PNG', 22, sigY + 14, sigSlotWidth - 4, sigSlotHeight - 4);
    }
    doc.text(data.refereeName, 20, sigY + 42);

    // Home Coach
    doc.text('HOME COACH SIGNATURE', 80, sigY + 10);
    doc.rect(80, sigY + 12, sigSlotWidth, sigSlotHeight);
    if (data.homeCoachSignature) {
        doc.addImage(data.homeCoachSignature, 'PNG', 82, sigY + 14, sigSlotWidth - 4, sigSlotHeight - 4);
    }

    // Away Coach
    doc.text('AWAY COACH SIGNATURE', 140, sigY + 10);
    doc.rect(140, sigY + 12, sigSlotWidth, sigSlotHeight);
    if (data.awayCoachSignature) {
        doc.addImage(data.awayCoachSignature, 'PNG', 142, sigY + 14, sigSlotWidth - 4, sigSlotHeight - 4);
    }

    // Footer
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(148, 163, 184);
        doc.text('THIS IS A LEGALLY BINDING DIGITAL PROTOCOL GENERATED BY PLYAZ.NET', 105, 285, { align: 'center' });
    }

    doc.save(`protocol-${data.homeTeam}-vs-${data.awayTeam}-${new Date().getTime()}.pdf`);
};
