import { jsPDF } from 'jspdf';
import 'jspdf-autotable';

interface MatchReportData {
    homeTeam: string;
    awayTeam: string;
    homeScore: number;
    awayScore: number;
    date: string;
    venue: string;
    competition: string;
    events: Array<{ minute: string; type: string; player: string; team: string }>;
}

export const generateMatchReport = (data: MatchReportData) => {
    const doc = new jsPDF();
    const brandPurple = '#7C3AED';
    const brandOrange = '#F97316';

    // Header
    doc.setFillColor(15, 23, 42); // slate-900
    doc.rect(0, 0, 210, 40, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('PLYAZ MATCH PROTOCOL', 105, 20, { align: 'center' });
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(data.competition.toUpperCase(), 105, 30, { align: 'center' });

    // Match Info
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(12);
    doc.text(`DATE: ${data.date}`, 20, 50);
    doc.text(`VENUE: ${data.venue}`, 20, 58);

    // Scoreboard
    doc.setDrawColor(226, 232, 240);
    doc.line(20, 65, 190, 65);

    doc.setFontSize(20);
    doc.text(data.homeTeam.toUpperCase(), 60, 85, { align: 'right' });
    
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(85, 70, 40, 25, 5, 5, 'F');
    doc.setTextColor(brandOrange);
    doc.setFontSize(30);
    doc.text(`${data.homeScore} : ${data.awayScore}`, 105, 88, { align: 'center' });
    
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(20);
    doc.text(data.awayTeam.toUpperCase(), 150, 85, { align: 'left' });

    // Events Table
    if (data.events.length > 0) {
        doc.setFontSize(14);
        doc.text('MATCH EVENTS', 20, 115);
        
        (doc as any).autoTable({
            startY: 120,
            head: [['MIN', 'EVENT', 'PLAYER', 'TEAM']],
            body: data.events.map(e => [e.minute, e.type.toUpperCase(), e.player, e.team]),
            headStyles: { fillColor: [124, 58, 237] }, // brandPurple
            styles: { fontSize: 10, cellPadding: 5 },
            margin: { left: 20, right: 20 }
        });
    } else {
        doc.setFontSize(10);
        doc.setTextColor(100, 116, 139);
        doc.text('No major events recorded for this match.', 105, 120, { align: 'center' });
    }

    // Footer
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(148, 163, 184);
        doc.text('GENERATED BY PLYAZ.NET — PROPELLING ELITE TALENT', 105, 285, { align: 'center' });
    }

    doc.save(`match-report-${data.homeTeam}-vs-${data.awayTeam}.pdf`);
};
